from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
# https://docs.astral.sh/uv/reference/settings/#pip_no-sources
from future import standard_library
standard_library.install_aliases()
[pip]
no-sources = true
