# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-11T13:56:48+00:00

from enum import Enum
from typing import Any, Dict, List, Optional, Union

AlwaysOffSampler = Optional


AlwaysOnSampler = Optional


class AttributeLimits:

    def __init__(self, attribute_value_length_limit=None, attribute_count_limit=None):
        self.attribute_value_length_limit = attribute_value_length_limit
        self.attribute_count_limit = attribute_count_limit


Value = List


Value1 = List


Value2 = List


class AttributeType(Enum):
    string = "string"
    bool = "bool"
    int = "int"
    double = "double"
    string_array = "string_array"
    bool_array = "bool_array"
    int_array = "int_array"
    double_array = "double_array"


B3MultiPropagator = Optional


B3Propagator = Optional


BaggagePropagator = Optional


class Base2ExponentialBucketHistogramAggregation:

    def __init__(self, max_scale=None, max_size=None, record_min_max=None):
        self.max_scale = max_scale
        self.max_size = max_size
        self.record_min_max = record_min_max


class CardinalityLimits:

    def __init__(self, default=None, counter=None, gauge=None, histogram=None, observable_counter=None, observable_gauge=None, observable_up_down_counter=None, up_down_counter=None):
        self.default = default
        self.counter = counter
        self.gauge = gauge
        self.histogram = histogram
        self.observable_counter = observable_counter
        self.observable_gauge = observable_gauge
        self.observable_up_down_counter = observable_up_down_counter
        self.up_down_counter = up_down_counter


ConsoleExporter = Optional


DefaultAggregation = Optional


Distribution = Dict


DropAggregation = Optional


class ExemplarFilter(Enum):
    always_on = "always_on"
    always_off = "always_off"
    trace_based = "trace_based"


ExperimentalComposableAlwaysOffSampler = Optional


ExperimentalComposableAlwaysOnSampler = Optional


class ExperimentalComposableProbabilitySampler:

    def __init__(self, ratio=None):
        self.ratio = ratio


class ExperimentalComposableRuleBasedSamplerRuleAttributePatterns:

    def __init__(self, key=None, included=None, excluded=None):
        self.key = key
        self.included = included
        self.excluded = excluded


class ExperimentalComposableRuleBasedSamplerRuleAttributeValues:

    def __init__(self, key=None, values=None):
        self.key = key
        self.values = values


ExperimentalContainerResourceDetector = Optional


ExperimentalHostResourceDetector = Optional


class ExperimentalHttpClientInstrumentation:

    def __init__(self, request_captured_headers=None, response_captured_headers=None, known_methods=None):
        self.request_captured_headers = request_captured_headers
        self.response_captured_headers = response_captured_headers
        self.known_methods = known_methods


class ExperimentalHttpServerInstrumentation:

    def __init__(self, request_captured_headers=None, response_captured_headers=None, known_methods=None):
        self.request_captured_headers = request_captured_headers
        self.response_captured_headers = response_captured_headers
        self.known_methods = known_methods


ExperimentalLanguageSpecificInstrumentation = Dict[
    str, Dict
]


class ExperimentalMeterConfig:

    def __init__(self, enabled=None):
        self.enabled = enabled


class ExperimentalMeterMatcherAndConfig:

    def __init__(self, name=None, config=None):
        self.name = name
        self.config = config


class ExperimentalOtlpFileExporter:

    def __init__(self, output_stream=None):
        self.output_stream = output_stream


class ExperimentalProbabilitySampler:

    def __init__(self, ratio=None):
        self.ratio = ratio


ExperimentalProcessResourceDetector = Optional


class ExperimentalPrometheusTranslationStrategy(Enum):
    underscore_escaping_with_suffixes = "underscore_escaping_with_suffixes"
    underscore_escaping_without_suffixes_development = (
        "underscore_escaping_without_suffixes/development"
    )
    no_utf8_escaping_with_suffixes_development = (
        "no_utf8_escaping_with_suffixes/development"
    )
    no_translation_development = "no_translation/development"


class ExperimentalSemconvConfig:

    def __init__(self, version=None, experimental=None, dual_emit=None):
        self.version = version
        self.experimental = experimental
        self.dual_emit = dual_emit


ExperimentalServiceResourceDetector = Optional


class ExperimentalSpanParent(Enum):
    none = "none"
    remote = "remote"
    local = "local"


class ExperimentalTracerConfig:

    def __init__(self, enabled=None):
        self.enabled = enabled


class ExperimentalTracerMatcherAndConfig:

    def __init__(self, name=None, config=None):
        self.name = name
        self.config = config


class ExperimentalUrlSanitization:

    def __init__(self, sensitive_query_parameters=None):
        self.sensitive_query_parameters = sensitive_query_parameters


class ExplicitBucketHistogramAggregation:

    def __init__(self, boundaries=None, record_min_max=None):
        self.boundaries = boundaries
        self.record_min_max = record_min_max


class ExporterDefaultHistogramAggregation(Enum):
    explicit_bucket_histogram = "explicit_bucket_histogram"
    base2_exponential_bucket_histogram = "base2_exponential_bucket_histogram"


class ExporterTemporalityPreference(Enum):
    cumulative = "cumulative"
    delta = "delta"
    low_memory = "low_memory"


class GrpcTls:

    def __init__(self, ca_file=None, key_file=None, cert_file=None, insecure=None):
        self.ca_file = ca_file
        self.key_file = key_file
        self.cert_file = cert_file
        self.insecure = insecure


class HttpTls:

    def __init__(self, ca_file=None, key_file=None, cert_file=None):
        self.ca_file = ca_file
        self.key_file = key_file
        self.cert_file = cert_file


class IncludeExclude:

    def __init__(self, included=None, excluded=None):
        self.included = included
        self.excluded = excluded


class InstrumentType(Enum):
    counter = "counter"
    gauge = "gauge"
    histogram = "histogram"
    observable_counter = "observable_counter"
    observable_gauge = "observable_gauge"
    observable_up_down_counter = "observable_up_down_counter"
    up_down_counter = "up_down_counter"


LastValueAggregation = Optional


class LogRecordLimits:

    def __init__(self, attribute_value_length_limit=None, attribute_count_limit=None):
        self.attribute_value_length_limit = attribute_value_length_limit
        self.attribute_count_limit = attribute_count_limit


class NameStringValuePair:

    def __init__(self, name=None, value=None):
        self.name = name
        self.value = value


OpenCensusMetricProducer = Optional


class OtlpGrpcExporter:

    def __init__(self, endpoint=None, tls=None, headers=None, headers_list=None, compression=None, timeout=None):
        self.endpoint = endpoint
        self.tls = tls
        self.headers = headers
        self.headers_list = headers_list
        self.compression = compression
        self.timeout = timeout


class OtlpGrpcMetricExporter:

    def __init__(self, endpoint=None, tls=None, headers=None, headers_list=None, compression=None, timeout=None, temporality_preference=None, default_histogram_aggregation=None):
        self.endpoint = endpoint
        self.tls = tls
        self.headers = headers
        self.headers_list = headers_list
        self.compression = compression
        self.timeout = timeout
        self.temporality_preference = temporality_preference
        self.default_histogram_aggregation = default_histogram_aggregation


class OtlpHttpEncoding(Enum):
    protobuf = "protobuf"
    json = "json"


class OtlpHttpExporter:

    def __init__(self, endpoint=None, tls=None, headers=None, headers_list=None, compression=None, timeout=None, encoding=None):
        self.endpoint = endpoint
        self.tls = tls
        self.headers = headers
        self.headers_list = headers_list
        self.compression = compression
        self.timeout = timeout
        self.encoding = encoding


class OtlpHttpMetricExporter:

    def __init__(self, endpoint=None, tls=None, headers=None, headers_list=None, compression=None, timeout=None, encoding=None, temporality_preference=None, default_histogram_aggregation=None):
        self.endpoint = endpoint
        self.tls = tls
        self.headers = headers
        self.headers_list = headers_list
        self.compression = compression
        self.timeout = timeout
        self.encoding = encoding
        self.temporality_preference = temporality_preference
        self.default_histogram_aggregation = default_histogram_aggregation


class SeverityNumber(Enum):
    trace = "trace"
    trace2 = "trace2"
    trace3 = "trace3"
    trace4 = "trace4"
    debug = "debug"
    debug2 = "debug2"
    debug3 = "debug3"
    debug4 = "debug4"
    info = "info"
    info2 = "info2"
    info3 = "info3"
    info4 = "info4"
    warn = "warn"
    warn2 = "warn2"
    warn3 = "warn3"
    warn4 = "warn4"
    error = "error"
    error2 = "error2"
    error3 = "error3"
    error4 = "error4"
    fatal = "fatal"
    fatal2 = "fatal2"
    fatal3 = "fatal3"
    fatal4 = "fatal4"


class SpanExporter:

    def __init__(self, otlp_http=None, otlp_grpc=None, otlp_file_development=None, console=None):
        self.otlp_http = otlp_http
        self.otlp_grpc = otlp_grpc
        self.otlp_file_development = otlp_file_development
        self.console = console


class SpanKind(Enum):
    internal = "internal"
    server = "server"
    client = "client"
    producer = "producer"
    consumer = "consumer"


class SpanLimits:

    def __init__(self, attribute_value_length_limit=None, attribute_count_limit=None, event_count_limit=None, link_count_limit=None, event_attribute_count_limit=None, link_attribute_count_limit=None):
        self.attribute_value_length_limit = attribute_value_length_limit
        self.attribute_count_limit = attribute_count_limit
        self.event_count_limit = event_count_limit
        self.link_count_limit = link_count_limit
        self.event_attribute_count_limit = event_attribute_count_limit
        self.link_attribute_count_limit = link_attribute_count_limit


SumAggregation = Optional


TraceContextPropagator = Optional


class TraceIdRatioBasedSampler:

    def __init__(self, ratio=None):
        self.ratio = ratio


class ViewSelector:

    def __init__(self, instrument_name=None, instrument_type=None, unit=None, meter_name=None, meter_version=None, meter_schema_url=None):
        self.instrument_name = instrument_name
        self.instrument_type = instrument_type
        self.unit = unit
        self.meter_name = meter_name
        self.meter_version = meter_version
        self.meter_schema_url = meter_schema_url


class Aggregation:

    def __init__(self, default=None, drop=None, explicit_bucket_histogram=None, base2_exponential_bucket_histogram=None, last_value=None, sum=None):
        self.default = default
        self.drop = drop
        self.explicit_bucket_histogram = explicit_bucket_histogram
        self.base2_exponential_bucket_histogram = base2_exponential_bucket_histogram
        self.last_value = last_value
        self.sum = sum


class AttributeNameValue:

    def __init__(self, name=None, value=None, type=None):
        self.name = name
        self.value = value
        self.type = type


class BatchSpanProcessor:

    def __init__(self, exporter=None, schedule_delay=None, export_timeout=None, max_queue_size=None, max_export_batch_size=None):
        self.exporter = exporter
        self.schedule_delay = schedule_delay
        self.export_timeout = export_timeout
        self.max_queue_size = max_queue_size
        self.max_export_batch_size = max_export_batch_size


class ConsoleMetricExporter:

    def __init__(self, temporality_preference=None, default_histogram_aggregation=None):
        self.temporality_preference = temporality_preference
        self.default_histogram_aggregation = default_histogram_aggregation


class ExperimentalCodeInstrumentation:

    def __init__(self, semconv=None):
        self.semconv = semconv


class ExperimentalDbInstrumentation:

    def __init__(self, semconv=None):
        self.semconv = semconv


class ExperimentalGenAiInstrumentation:

    def __init__(self, semconv=None):
        self.semconv = semconv


class ExperimentalHttpInstrumentation:

    def __init__(self, semconv=None, client=None, server=None):
        self.semconv = semconv
        self.client = client
        self.server = server


class ExperimentalLoggerConfig:

    def __init__(self, enabled=None, minimum_severity=None, trace_based=None):
        self.enabled = enabled
        self.minimum_severity = minimum_severity
        self.trace_based = trace_based


class ExperimentalLoggerMatcherAndConfig:

    def __init__(self, name=None, config=None):
        self.name = name
        self.config = config


class ExperimentalMessagingInstrumentation:

    def __init__(self, semconv=None):
        self.semconv = semconv


class ExperimentalMeterConfigurator:

    def __init__(self, default_config=None, meters=None):
        self.default_config = default_config
        self.meters = meters


class ExperimentalOtlpFileMetricExporter:

    def __init__(self, output_stream=None, temporality_preference=None, default_histogram_aggregation=None):
        self.output_stream = output_stream
        self.temporality_preference = temporality_preference
        self.default_histogram_aggregation = default_histogram_aggregation


class ExperimentalPrometheusMetricExporter:

    def __init__(self, host=None, port=None, without_scope_info=None, without_target_info_development=None, with_resource_constant_labels=None, translation_strategy=None):
        self.host = host
        self.port = port
        self.without_scope_info = without_scope_info
        self.without_target_info_development = without_target_info_development
        self.with_resource_constant_labels = with_resource_constant_labels
        self.translation_strategy = translation_strategy


class ExperimentalResourceDetector:

    def __init__(self, container=None, host=None, process=None, service=None):
        self.container = container
        self.host = host
        self.process = process
        self.service = service


class ExperimentalRpcInstrumentation:

    def __init__(self, semconv=None):
        self.semconv = semconv


class ExperimentalSanitization:

    def __init__(self, url=None):
        self.url = url


class ExperimentalTracerConfigurator:

    def __init__(self, default_config=None, tracers=None):
        self.default_config = default_config
        self.tracers = tracers


class LogRecordExporter:

    def __init__(self, otlp_http=None, otlp_grpc=None, otlp_file_development=None, console=None):
        self.otlp_http = otlp_http
        self.otlp_grpc = otlp_grpc
        self.otlp_file_development = otlp_file_development
        self.console = console


class MetricProducer:

    def __init__(self, opencensus=None):
        self.opencensus = opencensus


class PullMetricExporter:

    def __init__(self, prometheus_development=None):
        self.prometheus_development = prometheus_development


class PullMetricReader:

    def __init__(self, exporter=None, producers=None, cardinality_limits=None):
        self.exporter = exporter
        self.producers = producers
        self.cardinality_limits = cardinality_limits


class PushMetricExporter:

    def __init__(self, otlp_http=None, otlp_grpc=None, otlp_file_development=None, console=None):
        self.otlp_http = otlp_http
        self.otlp_grpc = otlp_grpc
        self.otlp_file_development = otlp_file_development
        self.console = console


class SimpleLogRecordProcessor:

    def __init__(self, exporter=None):
        self.exporter = exporter


class SimpleSpanProcessor:

    def __init__(self, exporter=None):
        self.exporter = exporter


class SpanProcessor:

    def __init__(self, batch=None, simple=None):
        self.batch = batch
        self.simple = simple


class TextMapPropagator:

    def __init__(self, tracecontext=None, baggage=None, b3=None, b3multi=None):
        self.tracecontext = tracecontext
        self.baggage = baggage
        self.b3 = b3
        self.b3multi = b3multi


class ViewStream:

    def __init__(self, name=None, description=None, aggregation=None, aggregation_cardinality_limit=None, attribute_keys=None):
        self.name = name
        self.description = description
        self.aggregation = aggregation
        self.aggregation_cardinality_limit = aggregation_cardinality_limit
        self.attribute_keys = attribute_keys


class BatchLogRecordProcessor:

    def __init__(self, exporter=None, schedule_delay=None, export_timeout=None, max_queue_size=None, max_export_batch_size=None):
        self.exporter = exporter
        self.schedule_delay = schedule_delay
        self.export_timeout = export_timeout
        self.max_queue_size = max_queue_size
        self.max_export_batch_size = max_export_batch_size


class ExperimentalGeneralInstrumentation:

    def __init__(self, http=None, code=None, db=None, gen_ai=None, messaging=None, rpc=None, sanitization=None, stability_opt_in_list=None):
        self.http = http
        self.code = code
        self.db = db
        self.gen_ai = gen_ai
        self.messaging = messaging
        self.rpc = rpc
        self.sanitization = sanitization
        self.stability_opt_in_list = stability_opt_in_list


class ExperimentalInstrumentation:

    def __init__(self, general=None, cpp=None, dotnet=None, erlang=None, go=None, java=None, js=None, php=None, python=None, ruby=None, rust=None, swift=None):
        self.general = general
        self.cpp = cpp
        self.dotnet = dotnet
        self.erlang = erlang
        self.go = go
        self.java = java
        self.js = js
        self.php = php
        self.python = python
        self.ruby = ruby
        self.rust = rust
        self.swift = swift


class ExperimentalLoggerConfigurator:

    def __init__(self, default_config=None, loggers=None):
        self.default_config = default_config
        self.loggers = loggers


class ExperimentalResourceDetection:

    def __init__(self, attributes=None, detectors=None):
        self.attributes = attributes
        self.detectors = detectors


class LogRecordProcessor:

    def __init__(self, batch=None, simple=None):
        self.batch = batch
        self.simple = simple


class PeriodicMetricReader:

    def __init__(self, exporter=None, interval=None, timeout=None, producers=None, cardinality_limits=None):
        self.exporter = exporter
        self.interval = interval
        self.timeout = timeout
        self.producers = producers
        self.cardinality_limits = cardinality_limits


class Propagator:

    def __init__(self, composite=None, composite_list=None):
        self.composite = composite
        self.composite_list = composite_list


class Resource:

    def __init__(self, attributes=None, detection_development=None, schema_url=None, attributes_list=None):
        self.attributes = attributes
        self.detection_development = detection_development
        self.schema_url = schema_url
        self.attributes_list = attributes_list


class View:

    def __init__(self, selector=None, stream=None):
        self.selector = selector
        self.stream = stream


class LoggerProvider:

    def __init__(self, processors=None, limits=None, logger_configurator_development=None):
        self.processors = processors
        self.limits = limits
        self.logger_configurator_development = logger_configurator_development


class MetricReader:

    def __init__(self, periodic=None, pull=None):
        self.periodic = periodic
        self.pull = pull


class MeterProvider:

    def __init__(self, readers=None, views=None, exemplar_filter=None, meter_configurator_development=None):
        self.readers = readers
        self.views = views
        self.exemplar_filter = exemplar_filter
        self.meter_configurator_development = meter_configurator_development


class OpenTelemetryConfiguration:

    def __init__(self, file_format=None, disabled=None, log_level=None, attribute_limits=None, logger_provider=None, meter_provider=None, propagator=None, tracer_provider=None, resource=None, instrumentation_development=None, distribution=None):
        self.file_format = file_format
        self.disabled = disabled
        self.log_level = log_level
        self.attribute_limits = attribute_limits
        self.logger_provider = logger_provider
        self.meter_provider = meter_provider
        self.propagator = propagator
        self.tracer_provider = tracer_provider
        self.resource = resource
        self.instrumentation_development = instrumentation_development
        self.distribution = distribution


class ExperimentalComposableParentThresholdSampler:

    def __init__(self, root=None):
        self.root = root


class ExperimentalComposableRuleBasedSampler:

    def __init__(self, rules=None):
        self.rules = rules


class ExperimentalComposableRuleBasedSamplerRule:
    """
    A rule for ExperimentalComposableRuleBasedSampler. A rule can have multiple match conditions - the sampler will be applied if all match.
    If no conditions are specified, the rule matches all spans that reach it.

    """

    def __init__(self, sampler=None, attribute_values=None, attribute_patterns=None, span_kinds=None, parent=None):
        self.sampler = sampler
        self.attribute_values = attribute_values
        self.attribute_patterns = attribute_patterns
        self.span_kinds = span_kinds
        self.parent = parent


class ExperimentalComposableSampler:

    def __init__(self, always_off=None, always_on=None, parent_threshold=None, probability=None, rule_based=None):
        self.always_off = always_off
        self.always_on = always_on
        self.parent_threshold = parent_threshold
        self.probability = probability
        self.rule_based = rule_based


class ExperimentalJaegerRemoteSampler:

    def __init__(self, endpoint=None, initial_sampler=None, interval=None):
        self.endpoint = endpoint
        self.initial_sampler = initial_sampler
        self.interval = interval


class ParentBasedSampler:

    def __init__(self, root=None, remote_parent_sampled=None, remote_parent_not_sampled=None, local_parent_sampled=None, local_parent_not_sampled=None):
        self.root = root
        self.remote_parent_sampled = remote_parent_sampled
        self.remote_parent_not_sampled = remote_parent_not_sampled
        self.local_parent_sampled = local_parent_sampled
        self.local_parent_not_sampled = local_parent_not_sampled


class Sampler:

    def __init__(self, always_off=None, always_on=None, composite_development=None, jaeger_remote_development=None, parent_based=None, probability_development=None, trace_id_ratio_based=None):
        self.always_off = always_off
        self.always_on = always_on
        self.composite_development = composite_development
        self.jaeger_remote_development = jaeger_remote_development
        self.parent_based = parent_based
        self.probability_development = probability_development
        self.trace_id_ratio_based = trace_id_ratio_based


class TracerProvider:

    def __init__(self, processors=None, limits=None, sampler=None, tracer_configurator_development=None):
        self.processors = processors
        self.limits = limits
        self.sampler = sampler
        self.tracer_configurator_development = tracer_configurator_development
