# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-11T13:56:48+00:00

from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict, List, Optional, Union

AlwaysOffSampler = Optional


AlwaysOnSampler = Optional


class AttributeLimits:
    attribute_value_length_limit = None
    attribute_count_limit = None


Value = List


Value1 = List


Value2 = List


class AttributeType(Enum):
    string = "string"
    bool = "bool"
    int = "int"
    double = "double"
    string_array = "string_array"
    bool_array = "bool_array"
    int_array = "int_array"
    double_array = "double_array"


B3MultiPropagator = Optional


B3Propagator = Optional


BaggagePropagator = Optional


class Base2ExponentialBucketHistogramAggregation:
    max_scale = None
    max_size = None
    record_min_max = None


class CardinalityLimits:
    default = None
    counter = None
    gauge = None
    histogram = None
    observable_counter = None
    observable_gauge = None
    observable_up_down_counter = None
    up_down_counter = None


ConsoleExporter = Optional


DefaultAggregation = Optional


Distribution = Dict


DropAggregation = Optional


class ExemplarFilter(Enum):
    always_on = "always_on"
    always_off = "always_off"
    trace_based = "trace_based"


ExperimentalComposableAlwaysOffSampler = Optional


ExperimentalComposableAlwaysOnSampler = Optional


class ExperimentalComposableProbabilitySampler:
    ratio = None


class ExperimentalComposableRuleBasedSamplerRuleAttributePatterns:
    key
    included = None
    excluded = None


class ExperimentalComposableRuleBasedSamplerRuleAttributeValues:
    key
    values


ExperimentalContainerResourceDetector = Optional


ExperimentalHostResourceDetector = Optional


class ExperimentalHttpClientInstrumentation:
    request_captured_headers = None
    response_captured_headers = None
    known_methods = None


class ExperimentalHttpServerInstrumentation:
    request_captured_headers = None
    response_captured_headers = None
    known_methods = None


ExperimentalLanguageSpecificInstrumentation = Dict[
    str, Dict
]


class ExperimentalMeterConfig:
    enabled = None


class ExperimentalMeterMatcherAndConfig:
    name
    config


class ExperimentalOtlpFileExporter:
    output_stream = None


class ExperimentalProbabilitySampler:
    ratio = None


ExperimentalProcessResourceDetector = Optional


class ExperimentalPrometheusTranslationStrategy(Enum):
    underscore_escaping_with_suffixes = "underscore_escaping_with_suffixes"
    underscore_escaping_without_suffixes_development = (
        "underscore_escaping_without_suffixes/development"
    )
    no_utf8_escaping_with_suffixes_development = (
        "no_utf8_escaping_with_suffixes/development"
    )
    no_translation_development = "no_translation/development"


class ExperimentalSemconvConfig:
    version = None
    experimental = None
    dual_emit = None


ExperimentalServiceResourceDetector = Optional


class ExperimentalSpanParent(Enum):
    none = "none"
    remote = "remote"
    local = "local"


class ExperimentalTracerConfig:
    enabled = None


class ExperimentalTracerMatcherAndConfig:
    name
    config


class ExperimentalUrlSanitization:
    sensitive_query_parameters = None


class ExplicitBucketHistogramAggregation:
    boundaries = None
    record_min_max = None


class ExporterDefaultHistogramAggregation(Enum):
    explicit_bucket_histogram = "explicit_bucket_histogram"
    base2_exponential_bucket_histogram = "base2_exponential_bucket_histogram"


class ExporterTemporalityPreference(Enum):
    cumulative = "cumulative"
    delta = "delta"
    low_memory = "low_memory"


class GrpcTls:
    ca_file = None
    key_file = None
    cert_file = None
    insecure = None


class HttpTls:
    ca_file = None
    key_file = None
    cert_file = None


class IncludeExclude:
    included = None
    excluded = None


class InstrumentType(Enum):
    counter = "counter"
    gauge = "gauge"
    histogram = "histogram"
    observable_counter = "observable_counter"
    observable_gauge = "observable_gauge"
    observable_up_down_counter = "observable_up_down_counter"
    up_down_counter = "up_down_counter"


LastValueAggregation = Optional


class LogRecordLimits:
    attribute_value_length_limit = None
    attribute_count_limit = None


class NameStringValuePair:
    name
    value


OpenCensusMetricProducer = Optional


class OtlpGrpcExporter:
    endpoint = None
    tls = None
    headers = None
    headers_list = None
    compression = None
    timeout = None


class OtlpGrpcMetricExporter:
    endpoint = None
    tls = None
    headers = None
    headers_list = None
    compression = None
    timeout = None
    temporality_preference = None
    default_histogram_aggregation    = None


class OtlpHttpEncoding(Enum):
    protobuf = "protobuf"
    json = "json"


class OtlpHttpExporter:
    endpoint = None
    tls = None
    headers = None
    headers_list = None
    compression = None
    timeout = None
    encoding = None


class OtlpHttpMetricExporter:
    endpoint = None
    tls = None
    headers = None
    headers_list = None
    compression = None
    timeout = None
    encoding = None
    temporality_preference = None
    default_histogram_aggregation    = None


class SeverityNumber(Enum):
    trace = "trace"
    trace2 = "trace2"
    trace3 = "trace3"
    trace4 = "trace4"
    debug = "debug"
    debug2 = "debug2"
    debug3 = "debug3"
    debug4 = "debug4"
    info = "info"
    info2 = "info2"
    info3 = "info3"
    info4 = "info4"
    warn = "warn"
    warn2 = "warn2"
    warn3 = "warn3"
    warn4 = "warn4"
    error = "error"
    error2 = "error2"
    error3 = "error3"
    error4 = "error4"
    fatal = "fatal"
    fatal2 = "fatal2"
    fatal3 = "fatal3"
    fatal4 = "fatal4"


class SpanExporter:
    otlp_http = None
    otlp_grpc = None
    otlp_file_development = None
    console = None


class SpanKind(Enum):
    internal = "internal"
    server = "server"
    client = "client"
    producer = "producer"
    consumer = "consumer"


class SpanLimits:
    attribute_value_length_limit = None
    attribute_count_limit = None
    event_count_limit = None
    link_count_limit = None
    event_attribute_count_limit = None
    link_attribute_count_limit = None


SumAggregation = Optional


TraceContextPropagator = Optional


class TraceIdRatioBasedSampler:
    ratio = None


class ViewSelector:
    instrument_name = None
    instrument_type = None
    unit = None
    meter_name = None
    meter_version = None
    meter_schema_url = None


class Aggregation:
    default = None
    drop = None
    explicit_bucket_histogram = (
        None
    )
    base2_exponential_bucket_histogram    = None
    last_value = None
    sum = None


class AttributeNameValue:
    name
    value
    type = None


class BatchSpanProcessor:
    exporter
    schedule_delay = None
    export_timeout = None
    max_queue_size = None
    max_export_batch_size = None


class ConsoleMetricExporter:
    temporality_preference = None
    default_histogram_aggregation    = None


class ExperimentalCodeInstrumentation:
    semconv = None


class ExperimentalDbInstrumentation:
    semconv = None


class ExperimentalGenAiInstrumentation:
    semconv = None


class ExperimentalHttpInstrumentation:
    semconv = None
    client = None
    server = None


class ExperimentalLoggerConfig:
    enabled = None
    minimum_severity = None
    trace_based = None


class ExperimentalLoggerMatcherAndConfig:
    name
    config


class ExperimentalMessagingInstrumentation:
    semconv = None


class ExperimentalMeterConfigurator:
    default_config = None
    meters = None


class ExperimentalOtlpFileMetricExporter:
    output_stream = None
    temporality_preference = None
    default_histogram_aggregation    = None


class ExperimentalPrometheusMetricExporter:
    host = None
    port = None
    without_scope_info = None
    without_target_info_development = None
    with_resource_constant_labels = None
    translation_strategy    = None


class ExperimentalResourceDetector:
    container = None
    host = None
    process = None
    service = None


class ExperimentalRpcInstrumentation:
    semconv = None


class ExperimentalSanitization:
    url = None


class ExperimentalTracerConfigurator:
    default_config = None
    tracers = None


class LogRecordExporter:
    otlp_http = None
    otlp_grpc = None
    otlp_file_development = None
    console = None


class MetricProducer:
    opencensus = None


class PullMetricExporter:
    prometheus_development = (
        None
    )


class PullMetricReader:
    exporter
    producers = None
    cardinality_limits = None


class PushMetricExporter:
    otlp_http = None
    otlp_grpc = None
    otlp_file_development = None
    console = None


class SimpleLogRecordProcessor:
    exporter


class SimpleSpanProcessor:
    exporter


class SpanProcessor:
    batch = None
    simple = None


class TextMapPropagator:
    tracecontext = None
    baggage = None
    b3 = None
    b3multi = None


class ViewStream:
    name = None
    description = None
    aggregation = None
    aggregation_cardinality_limit = None
    attribute_keys = None


class BatchLogRecordProcessor:
    exporter
    schedule_delay = None
    export_timeout = None
    max_queue_size = None
    max_export_batch_size = None


class ExperimentalGeneralInstrumentation:
    http = None
    code = None
    db = None
    gen_ai = None
    messaging = None
    rpc = None
    sanitization = None
    stability_opt_in_list = None


class ExperimentalInstrumentation:
    general = None
    cpp = None
    dotnet = None
    erlang = None
    go = None
    java = None
    js = None
    php = None
    python = None
    ruby = None
    rust = None
    swift = None


class ExperimentalLoggerConfigurator:
    default_config = None
    loggers = None


class ExperimentalResourceDetection:
    attributes = None
    detectors = None


class LogRecordProcessor:
    batch = None
    simple = None


class PeriodicMetricReader:
    exporter
    interval = None
    timeout = None
    producers = None
    cardinality_limits = None


class Propagator:
    composite = None
    composite_list = None


class Resource:
    attributes = None
    detection_development = None
    schema_url = None
    attributes_list = None


class View:
    selector
    stream


class LoggerProvider:
    processors
    limits = None
    logger_configurator_development    = None


class MetricReader:
    periodic = None
    pull = None


class MeterProvider:
    readers
    views = None
    exemplar_filter = None
    meter_configurator_development = (
        None
    )


class OpenTelemetryConfiguration:
    file_format
    disabled = None
    log_level = None
    attribute_limits = None
    logger_provider = None
    meter_provider = None
    propagator = None
    tracer_provider = None
    resource = None
    instrumentation_development = None
    distribution = None


class ExperimentalComposableParentThresholdSampler:
    root


class ExperimentalComposableRuleBasedSampler:
    rules = None


class ExperimentalComposableRuleBasedSamplerRule:
    """
    A rule for ExperimentalComposableRuleBasedSampler. A rule can have multiple match conditions - the sampler will be applied if all match.
    If no conditions are specified, the rule matches all spans that reach it.

    """

    sampler
    attribute_values    = None
    attribute_patterns    = None
    span_kinds = None
    parent = None


class ExperimentalComposableSampler:
    always_off = None
    always_on = None
    parent_threshold    = None
    probability = None
    rule_based = None


class ExperimentalJaegerRemoteSampler:
    endpoint
    initial_sampler
    interval = None


class ParentBasedSampler:
    root = None
    remote_parent_sampled = None
    remote_parent_not_sampled = None
    local_parent_sampled = None
    local_parent_not_sampled = None


class Sampler:
    always_off = None
    always_on = None
    composite_development = None
    jaeger_remote_development = None
    parent_based = None
    probability_development = None
    trace_id_ratio_based = None


class TracerProvider:
    processors
    limits = None
    sampler = None
    tracer_configurator_development    = None
